# Generated by Django 3.1.8 on 2023-02-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('teacher_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studentregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('student_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('total', models.CharField(max_length=40)),
                ('mymark', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hodregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('hod_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
